# Generated by Django 5.0.6 on 2024-10-23 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('tiempo_conocimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_propietarios/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firma_propietarios/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('actividadeconomica', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_empresa/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
                ('link', models.CharField(default='1', max_length=300)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='Personal.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.FileField(blank=True, null=True, upload_to='Reportes/')),
                ('descripcion', models.TextField(null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha creación:')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización:')),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.empleado', verbose_name='Empleado:')),
            ],
        ),
    ]
