# Generated by Django 5.0.6 on 2024-12-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mod', models.CharField(max_length=100)),
                ('fabricacion_mod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_car', models.CharField(max_length=50)),
                ('precio_car', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa_com', models.CharField(max_length=10, unique=True)),
                ('fkid_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pro', models.CharField(max_length=100)),
                ('apellido_pro', models.CharField(max_length=100)),
                ('email_pro', models.EmailField(max_length=254)),
                ('telefono_pro', models.CharField(max_length=15)),
                ('fkid_ciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkid_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.carro')),
                ('fkid_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.propietario')),
            ],
        ),
    ]
