# Generated by Django 5.0.6 on 2024-12-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='placa_com',
            new_name='placa_car',
        ),
    ]
